### ISSUE TITLE
Click outside the modal

### ISSUE THREAD

**Issue by fracarma** [pozil/sfdc-ui-modal-sample#1]
A nice-to-have would be to get the modal closed when the user click outside the modal__container. I don't really find a nice solution in Lightning, any ideas?
Thanks for this nice component anyway, I don't really understand why Salesforce is not providing this as a native lightning component!

**Comment by pozil** [comment]
Hi @fracarma,

I did not implement that since this is not part of SLDS.

However, this can easily be achieved by having an `onlick` attribute on the backdrop div:
`<div class="slds-backdrop slds-backdrop--open"></div>`

The controller function attached to the `onclick` listener will just have to call the `closeModal` method I exposed to close the modal.

Cheers,

**Comment by fracarma** [comment]
Thanks, I will use this method!

**Comment by fracarma** [comment]
Sorry for bother, but just to know with locker service it seems we can't have an onclick attribute on a div.. So we should find another workaround.
